# Generated by Django 3.2.8 on 2021-10-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='author',
            name='join_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_login_date',
            field=models.DateTimeField(null=True),
        ),
    ]
