# Generated by Django 3.2.8 on 2021-10-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20211021_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='reponse_text',
            new_name='response_text',
        ),
    ]
