# Generated by Django 3.2.8 on 2021-10-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_rename_reponse_text_response_response_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(upload_to='static/avatar'),
        ),
    ]
